//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTR_01.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public int sizeDB100 {
            get {
                return ((int)(this["sizeDB100"]));
            }
            set {
                this["sizeDB100"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("496")]
        public int sizeDB101 {
            get {
                return ((int)(this["sizeDB101"]));
            }
            set {
                this["sizeDB101"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99")]
        public int sizeDB200 {
            get {
                return ((int)(this["sizeDB200"]));
            }
            set {
                this["sizeDB200"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("232")]
        public int SizeDB201 {
            get {
                return ((int)(this["SizeDB201"]));
            }
            set {
                this["SizeDB201"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public string sizeDB202 {
            get {
                return ((string)(this["sizeDB202"]));
            }
            set {
                this["sizeDB202"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Documents\\LTR\\LTR01\\LTR_01\\LTR_01\\bin\\Debug")]
        public string PathRig {
            get {
                return ((string)(this["PathRig"]));
            }
            set {
                this["PathRig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Documents\\LTR\\LTR01\\LTR_01\\LTR_01\\bin\\Debug\\Process1.xls")]
        public string PathCallMag {
            get {
                return ((string)(this["PathCallMag"]));
            }
            set {
                this["PathCallMag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Admin {
            get {
                return ((bool)(this["Admin"]));
            }
            set {
                this["Admin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123")]
        public string AdminPwd {
            get {
                return ((string)(this["AdminPwd"]));
            }
            set {
                this["AdminPwd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.0.1")]
        public string PLCAddress {
            get {
                return ((string)(this["PLCAddress"]));
            }
            set {
                this["PLCAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RigNo {
            get {
                return ((string)(this["RigNo"]));
            }
            set {
                this["RigNo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>DN2</string>
  <string>DN3</string>
  <string>DN6</string>
  <string>DN10</string>
  <string>DN15</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SizeList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SizeList"]));
            }
            set {
                this["SizeList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Toto</string>
  <string>Tata</string>
  <string>Tutu</string>
  <string>Tete</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection OperatorList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OperatorList"]));
            }
            set {
                this["OperatorList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Elchinger</string>
  <string>Saunier</string>
  <string>Scherrer</string>
  <string>Tuaillon</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AdminList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AdminList"]));
            }
            set {
                this["AdminList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color red {
            get {
                return ((global::System.Drawing.Color)(this["red"]));
            }
            set {
                this["red"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LimeGreen")]
        public global::System.Drawing.Color green {
            get {
                return ((global::System.Drawing.Color)(this["green"]));
            }
            set {
                this["green"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gold")]
        public global::System.Drawing.Color yellow {
            get {
                return ((global::System.Drawing.Color)(this["yellow"]));
            }
            set {
                this["yellow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DodgerBlue")]
        public global::System.Drawing.Color blue {
            get {
                return ((global::System.Drawing.Color)(this["blue"]));
            }
            set {
                this["blue"] = value;
            }
        }
    }
}
